set_property PACKAGE_PIN D18 [get_ports LED1]
set_property PACKAGE_PIN T16 [get_ports SW1]
set_property PACKAGE_PIN V12 [get_ports AN]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports AN]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN W16 [get_ports TX_out]
set_property IOSTANDARD LVCMOS33 [get_ports TX_out]
set_property IOSTANDARD LVCMOS33 [get_ports RX_in]
set_property PACKAGE_PIN J15 [get_ports RX_in]

set_property PACKAGE_PIN T14 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property PACKAGE_PIN T16 [get_ports SW1]
set_property PACKAGE_PIN V12 [get_ports AN]
