# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MAXSENSOR.xdc

# Block Designs: bd/MAXONAR/MAXONAR.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MAXONAR || ORIG_REF_NAME==MAXONAR}]

# IP: bd/MAXONAR/ip/MAXONAR_processing_system7_0_0/MAXONAR_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MAXONAR_processing_system7_0_0 || ORIG_REF_NAME==MAXONAR_processing_system7_0_0}]

# XDC: bd/MAXONAR/MAXONAR_ooc.xdc
