fcanvas_actuator_label" id="translation_icon-menu" tabindex="-1" aria-hidden="true"></span></div><div class="nav_list_wrapper" id="nav_list_wrapper"><nav class="offcanvas_nav" role="navigation"><ul class="nav_breadcrumb" id="ul_left_nav_ancestors"><li itemscope="" itemtype="http://www.data-vocabulary.org/Breadcrumb" itemprop="breadcrumb"><a href="../../documentation-center.html?s_tid=CRUX_lftnav" itemprop="url"><span itemprop="title">Documentation Home</span></a></li></ul>
<ul class="nav_disambiguation"><li><a href="../index.html?s_tid=CRUX_lftnav">Polyspace Bug Finder</a>
</li>
<li itemscope="" itemtype="http://www.data-vocabulary.org/Breadcrumb" itemprop="breadcrumb"><a href="../review-results-1.html?s_tid=CRUX_lftnav" itemprop="url"><span itemprop="title">Review Analysis Results</span></a></li><li itemscope="" itemtype="http://www.data-vocabulary.org/Breadcrumb" itemprop="breadcrumb"><a href="../check-reference.html?s_tid=CRUX_lftnav" itemprop="url"><span itemprop="title">Polyspace
            Bug Finder Results</span></a></li><li itemscope="" itemtype="http://www.data-vocabulary.org/Breadcrumb" itemprop="breadcrumb"><a href="../coding-rule-reference.html?s_tid=CRUX_lftnav" itemprop="url"><span itemprop="title">Coding Standards</span></a></li><li itemscope="" itemtype="http://www.data-vocabulary.org/Breadcrumb" itemprop="breadcrumb"><a href="../cert-c-rules-and-recommendations.html?s_tid=CRUX_lftnav" itemprop="url"><span itemprop="title">CERT C Rules and Recommendations</span></a></li></ul><ul class="nav_scrollspy nav">
<li class="nav_scrollspy_function notranslate"><a href="#responsive_offcanvas">CERT C: Rec. MEM00-C</a></li>
<li class="nav_scrollspy_title" id="SSPY810-refentry">On this page</li>
<!--ADD_REFENTRY_TITLE_HERE 11--><li><a href="#d122e164063" class="intrnllnk">Description</a><ul class="nav"><li><a href="#d122e164065" class="intrnllnk">Rule Definition</a></li></ul><ul class="nav"><li><a href="#d122e164074" class="intrnllnk">Polyspace Implementation</a></li></ul></li><li><a href="#d122e164094" class="intrnllnk">Examples</a><ul class="nav"><li><a href="#d122e164096" class="intrnllnk">Invalid free of pointer</a></li></ul><ul class="nav"><li><a href="#d122e164192" class="intrnllnk">Deallocation of previously deallocated pointer</a></li></ul><ul class="nav"><li><a href="#d122e164251" class="intrnllnk">Use of previously freed pointer</a></li></ul></li><li><a href="#d122e164307" class="intrnllnk">Check Information</a></li><li><a href="#mw_6699c2df-cc0e-4453-bac0-d6d7ab395bbb_seealso" class="intrnllnk">See Also</a></li></ul>
</nav></div></nav>
<script src="../../includes/product/scripts/offcanvas_v2.js"></script></div><!--END.CLASS sidebar-offcanvas-->
<div class="offcanvas_content_container">
<div xmlns="http://www.w3.org/1999/xhtml" class="sticky_header_container"><div class="horizontal_nav"><div class="horizontal_nav_container"><div class="offcanvas_horizontal_nav"><div class="container-fluid"><div class="row"><div class="col-sm-12 hidden-xs"><nav class="navbar navbar-default" role="navigation" id="subnav"><div><ul class="nav navbar-nav crux_browse"><li id="crux_nav_documentation" class="crux_resource active"><a>All</a></li><li id="crux_nav_analysisopt" class="crux_resource"><a href="../referencelist.html?type=analysisopt&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Analysis Options</a></li><li id="crux_nav_runtimecheck" class="crux_resource"><a href="../referencelist.html?type=runtimecheck&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Polyspace Results</a></li><li id="crux_nav_function" class="crux_resource"><a href="../referencelist.html?type=function&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Functions</a></li><li id="crux_nav_reportgen" class="crux_resource"><a href="../referencelist.html?type=reportgen&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Report Components</a></li></ul></div></nav></div><div class="visible-xs"><div class="container-fluid"><div class="row"><div class="col-xs-9"><div class="mobile_crux_nav_trigger"><div class="btn-group"><button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resources<span class="icon-arrow-down icon_16"></span></button><ul class="dropdown-menu"><li id="crux_nav_mobile_documentation" class="crux_resource active"><a>All</a></li><li id="crux_nav_mobile_analysisopt" class="crux_resource"><a href="../referencelist.html?type=analysisopt&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Analysis Options</a></li><li id="crux_nav_mobile_runtimecheck" class="crux_resource"><a href="../referencelist.html?type=runtimecheck&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Polyspace Results</a></li><li id="crux_nav_mobile_function" class="crux_resource"><a href="../referencelist.html?type=function&amp;category=cert-c-rules-and-recommendations&amp;s_tid=CRUX_topnav">Functions</a></li><li id="crux_nav_mobile_reportgen" class="crux_resource"><a href="../referencelist.html?type=reportgen&amp;category=cert-c-rules-and-recommendations&a